spring:
  application:
    name: api-user-data
  profiles:
    default: dev
    active: dev
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: "health"